[package]
name = "maia"
version = "0.0.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
flate2 = "1.1.2"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
tar = "0.4.44"
xz = "0.1.0"
zip = "5.1.1"
